version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: fabrica_software
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=fabrica_software_db
    volumes:
      - db_fabrica_pg_data:/bitnami/postgresql

volumes:
  db_fabrica_pg_data:
